apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: appwrite
  annotations:
    version: v1.0.0
    description: "Appwrite"
spec:
  components:
    - name: appwrite
      type: webservice
      properties:
        image: appwrite/appwrite:1.3
        ports:
        - port: 6379
          expose: true
        env:
        - name: _APP_ENV
          value: "development"