# apiVersion: core.oam.dev/v1beta1
# kind: Application
# metadata:
#   # Name of the application which will be used to refer to it once deployed.
#   name: postgres
# spec:
#   # List of components that are part of the application.
#   components:
#       # Each component must have a name. The name will be used during the translation process
#       # to Kubernetes entities.
#     - name: postgres
#       # Each component is associated with a type. The type works as a template and defines
#       # how a high-level component will be translated into Kubernetes.
#       type: webservice
#       # Properties that can be configured for the user. This can be use to set the parameters
#       # that are defined by the component type.
#       image: postgres
#         ports:
#           - port: 8080:8080
#             expose: true
#         env:
#           - POSTGRES_PASSWORD: example
#       # Traits are extensions that augment the capabilities of a component. For example,
#       # changing the replication, importing a config map, etc.
#       # traits:
#       #   - type: <trait type>
#       #     properties:
#       #       <traits parameter values>


apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: postgresql
  annotations:
    version: v1.0.0
    description: "Postgres Database"
spec:
  components:
    - name: postgres
      type: webservice
      properties:
        image: postgres:14.2
        # cpu: "150m" 
        # memory: 256Mi
        ports:
        - port: 5432
          expose: true
        env:
        # - name: POSTGRES_DB
        #   value: "postgresdb"
        # - name: POSTGRES_USER
        #   value: "admin"
        - name: POSTGRES_PASSWORD
          value: "admin"
        # - name: PGDATA
        #   value: "/var/lib/postgresql/data/pgdata"
        # volumeMounts:
        #   emptyDir:
        #   - name: data
        #     mountPath: "/var/lib/postgresql/data"
        #     medium: ""